# Generated by Django 3.1 on 2022-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name': 'Пароль', 'verbose_name_plural': 'Пароли'},
        ),
        migrations.AddField(
            model_name='password',
            name='key',
            field=models.SlugField(null=True, unique=True, verbose_name='Ключ'),
        ),
    ]
