# Generated by Django 3.2 on 2022-10-25 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(null=True, unique=True, verbose_name='Ключ')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Пароли',
            },
        ),
    ]
