# Generated by Django 3.2 on 2022-11-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name': 'пароль', 'verbose_name_plural': 'пароли'},
        ),
        migrations.AlterField(
            model_name='password',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание для пароля', max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='password',
            name='key',
            field=models.SlugField(help_text='Придумайте ключ доступа для вашего пароля', null=True, unique=True, verbose_name='ключ'),
        ),
        migrations.AlterField(
            model_name='password',
            name='link',
            field=models.URLField(blank=True, help_text='Введите ссылка на ресурс, где используется пароль', null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=32, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
