# Generated by Django 3.2 on 2022-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20221230_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='check_unique',
            field=models.SlugField(help_text='Уникальность на урвне пользователя', null=True, unique=True, verbose_name='уникальность'),
        ),
    ]
