# Generated by Django 3.2 on 2023-03-23 17:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0003_alter_password_check_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='password',
            unique_together={('user', 'key')},
        ),
    ]
